# Generated by Django 2.2.4 on 2019-08-07 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('testmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='firstapp.TestModel')),
                ('price', models.IntegerField(default=10)),
            ],
            bases=('firstapp.testmodel',),
        ),
    ]
