# Generated by Django 2.2.4 on 2019-08-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_car_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=10, verbose_name='Price of Car'),
        ),
    ]
